In [1]:
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold
import numpy as np

In [27]:
X = np.array([[1,2], [3,4], [1,2], [3,4], [1,2], [3,4], [1,2], [3,4]])
# X = np.array([[1], [2], [3], [4], [5], [6], [7], [8]])
# X = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# X = np.array(['1', '2', '3', '4', '5', '6', '7', '8'])

# y = np.array([[0,0], [0,0], [0,1], [0,1], [1,1], [1,1], [1,0], [1,0]])
y = np.array([[0,4,5], [0,4,0], [0,4,1], [0,4,1], [1,4,1], [1,4,1], [1,4,0], [1,4,0]])

In [31]:
mskf = MultilabelStratifiedKFold(n_splits=2, shuffle=False, random_state=0)

In [32]:
for train_index, test_index in mskf.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1 5 6] TEST: [2 3 4 7]
TRAIN: [2 3 4 7] TEST: [0 1 5 6]


In [33]:
X_train

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [34]:
X

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [35]:
train_index

array([2, 3, 4, 7])